# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
    - id: shellcheck
      name: shellcheck
      description: Test shell scripts with shellcheck
      entry: shellcheck
      language: system
      types: [shell]
      require_serial: true # shellcheck can detect sourcing this way
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # - repo: https://github.com/koalaman/shellcheck-precommit
  #   rev: v0.7.2
  #   hooks:
  #     - id: shellcheck
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shfmt
